### ISSUE TITLE
Notifications SPAM

### ISSUE THREAD

**Issue by KurtFill** [elementary/wingpanel-indicator-notifications#178]
A company called OSTODAY.ORG has been causing pop ups on my Notifications system. I think we've been spammed. Anyway to block Notifications from a specific source?

**Comment by cassidyjames** [comment]
This is likely due to notifications in a third-party web browser, like Google Chrome, Opera, Brave, etc. In elementary OS you can block all notifications from an app (or "Other" notifications if the app doesn't integrate properly), but that's probably heavy-handed. Look in your browser's settings for notifications to disable them.
