### ISSUE TITLE
Ignores notification settings for safeeyes

### ISSUE THREAD

**Issue by nick87720z** [elementary/wingpanel-indicator-notifications#201]
I adapted safeeyes to be recognized by switchboard-plug-notifications as individual application by copying launcher to `~/.local/share/applications/` and adding mandated `X-GNOME-UsesNotifications=true` line. I disabled it from getting to notification center history, but this is simple ignored. Notifications from safeeyes get to history as always.

Elementary OS Hera
wingpanel-indicator-notifications-2.1.4+r429+pkg24-ubuntu5.1.2.1
switchboard-plug-notifications-2.1.7+r444+pkg380~ubuntu5.1.4.1

**Comment by danrabbit** [comment]
It looks like [safeeyes uses LibNotify](https://github.com/pscorek/SafeEyes/blob/master/safeeyes/Notification.py) instead of GLib.Notification, which means it doesn't automatically set the desktop info hint and so we can't match its notifications to settings

**Comment by danrabbit** [comment]
"app-name" is not the same thing as ID and it is defined as being optional in the old spec, so apps may not even send it at all. There is no definition for ID in the old notifications spec because features like a Notification Center or system wide notification options didn't exist.

Indeed notifications sent with GLib.Notification ignore the optional "app-name" key altogether because the localized display name is available from appinfo
