### ISSUE TITLE
KDE Connect notification does not work

### ISSUE THREAD

**Issue by diddy-boy** [elementary/wingpanel-indicator-notifications#205]
wanting to sync not just files but the battery level and send messages to and from my Android phone, I installed KDE connect
The app does not fire up but I can work around by using a temrinal to run 'KDEConnect-settings'
With this I can configure to connect to my phone but the KDE-Indicator will not run.
so overall it's kind of useless.
No message notification, no battery level readout.

Would be nice to have this feature usable.
I am currently Running Zorin OS 16 and Elementary OS 6 Beta 2.
I will buy / donate one or the other on release but I really like the look of Elementary OS but the phone syncing is a bit of a pain where as this just works on Zorin OS nut Zorin OS doesnt look as good

Thanks in advance
Rich

**Comment by danrabbit** [comment]
It sounds like the issue you're having here is with an app that requires an app-specific panel indicator to run. elementary OS doesn't support app-specific indicators. Connected devices that communicate their power state over UPower will automatically show up in the system power indicator. It's odd that notifications wouldn't be sent, but this sounds like a symptom of the larger issue of not being able to launch the KDE connect app.

I'm not really sure that it's within the scope of KDE connect to expect to run smoothly on other desktop environments than KDE Plasma. You could try filing issues there about the problems you're experiencing. But since this doens't seem to be an issue with saving missed notifications in the notification center, I'm going to close this issue report as "Out of scope"
